import Link from 'next/link';
import type { Metadata } from 'next';
import { ContactForm, Faq, MarketingFooter, MarketingNav } from '@/components/marketing';

export const metadata: Metadata = {
  title: 'Loop — the project tool that keeps itself updated',
  alternates: { canonical: '/' },
};

const FEATURES = [
  {
    icon: '⚡',
    title: 'Auto-Pilot board',
    body: 'GitHub events, chat and task activity feed a rules engine. Open a PR on a branch named PAY-12 and Loop proposes moving PAY-12 to Code Review — with the pull request attached as evidence.',
    tag: 'Differentiator',
  },
  {
    icon: '📊',
    title: 'Explainable health score',
    body: 'A 0–100 score per project from five weighted signals: overdue ratio, blocked chains, velocity trend, WIP overload and silent tasks. The maths is deterministic; AI only writes the summary.',
    tag: 'Differentiator',
  },
  {
    icon: '🔎',
    title: 'Ask the Workspace',
    body: 'Ask "what is blocking the release?" and get an answer with citations. Retrieval is filtered by your role first, so a client account can never pull internal chat into the answer.',
    tag: 'Differentiator',
  },
  { icon: '🗂', title: 'Kanban that bends', body: 'Six columns out of the box, fully editable per project. Drag on desktop, tap to move on mobile. Subtasks, dependencies, checklists, story points and bulk actions.' },
  { icon: '🏃', title: 'Sprints and burndown', body: 'Capacity planning, real burndown history written nightly, burnup, velocity across ten sprints, and blockers surfaced at the top of the sprint page.' },
  { icon: '📄', title: 'Docs with history', body: 'Rich text and markdown, code blocks, tables, nested pages, full version history and one-click restore. Mark a page shared to expose it to clients.' },
  { icon: '💬', title: 'Real-time chat', body: 'Project channels, DMs, threads, @mentions, reactions and file sharing over WebSocket, with presence and typing indicators.' },
  { icon: '⏱', title: 'Time tracking', body: 'Start-stop timers, manual entries, daily logs, hours by project and utilisation against each person’s weekly capacity.' },
  { icon: '🔐', title: 'Security you can audit', body: 'Google OAuth, verified email, rotating refresh tokens with reuse detection, RBAC in one middleware layer, rate limiting and an audit log for every privileged action.' },
];

const PLANS = [
  { name: 'Free', price: '$0', cadence: 'forever', seats: 'Up to 5 people', features: ['3 projects', 'Kanban, wiki and chat', 'Time tracking', 'Community support'], cta: 'Start free' },
  { name: 'Team', price: '$12', cadence: 'per user / month', seats: 'Up to 25 people', features: ['Unlimited projects', 'Sprints and analytics', 'Auto-Pilot board', 'GitHub integration', 'Priority support'], cta: 'Start free trial', featured: true },
  { name: 'Business', price: '$29', cadence: 'per user / month', seats: 'Unlimited', features: ['Everything in Team', 'Ask the Workspace', 'Client portal access', 'Audit log export', 'SSO ready · 99.9% SLA'], cta: 'Talk to us' },
];

const TESTIMONIALS = [
  { quote: 'Our board used to be two days stale by Wednesday. Now it argues with us when it is wrong, and it shows the commit that proves it.', name: 'Ava Sharma', role: 'Head of Engineering, Northwind Labs' },
  { quote: 'The health score is the first project metric my team has not immediately dismissed, because you can see exactly which five numbers produced it.', name: 'Rohan Mehta', role: 'Product Manager, Northwind Labs' },
  { quote: 'As a client I get progress and shared docs, and nothing else. That boundary is the reason we approved the rollout.', name: 'Nina Fischer', role: 'Programme Lead, Fischer & Co' },
];

const FAQ = [
  { q: 'How is this different from Jira with a chatbot?', a: 'A chatbot answers questions about a board somebody else has to keep updated. Loop watches real activity — commits, pull requests, chat, task events — and proposes the update itself. Every proposal carries the trigger, the evidence and a confidence score, and a human accepts or rejects it. Accepting writes to the audit log.' },
  { q: 'Can the AI change my board without asking?', a: 'Not unless you switch it on. By default every suggestion waits in an inbox. A project owner can enable auto-apply per project, and even then only rule-based suggestions above 90% confidence apply automatically — AI-matched ones are capped below that line on purpose.' },
  { q: 'Is the health score generated by a language model?', a: 'No. The number is arithmetic: five signals, fixed weights, published formula. The model is handed the finished numbers and asked to write two sentences of plain English. It cannot invent a figure because it never computes one.' },
  { q: 'What stops a client from seeing internal discussion?', a: 'Permissions are applied before retrieval, not after. A client account has no chat permission at all, and workspace search and the AI retriever both filter to shared documents and task progress before anything reaches the model.' },
  { q: 'Which models does it use?', a: 'Groq runs as the frontier provider for speed, with Gemini as the automatic fallback if Groq is unavailable or rate limited. Embeddings for retrieval come from Gemini. Without any key configured the product still works — retrieval falls back to keyword search and the rules engine keeps making suggestions.' },
  { q: 'Does it work on a phone?', a: 'It is built mobile first. The board supports drag and drop on a pointer and tap-to-move on touch, navigation collapses to a bottom bar, and every table scrolls rather than squashing.' },
];

export default function LandingPage() {
  return (
    <div className="min-h-dvh">
      <MarketingNav />

      <main id="main">
        {/* Hero */}
        <section className="relative overflow-hidden border-b">
          <div
            aria-hidden
            className="pointer-events-none absolute inset-x-0 -top-24 h-64 opacity-60 blur-3xl"
            style={{ background: 'radial-gradient(60% 60% at 50% 50%, var(--accent-soft), transparent)' }}
          />
          <div className="relative mx-auto max-w-6xl px-4 py-14 sm:px-6 sm:py-20 lg:py-24">
            <div className="mx-auto max-w-3xl text-center">
              <span className="badge bg-[var(--accent-soft)] text-[var(--accent)]">Jira + Notion + Slack + GitHub, in one place</span>
              <h1 className="mt-4 text-3xl font-bold leading-[1.1] tracking-[-0.03em] sm:text-5xl lg:text-6xl">
                The project tool that
                <br className="hidden sm:block" /> keeps itself updated
              </h1>
              <p className="mx-auto mt-4 max-w-2xl text-[15px] leading-relaxed text-[var(--text-muted)] sm:text-base">
                Every team already has the tools. The problem is that the board is always stale. Loop reads your real activity — commits, chat, task events —
                and proposes the updates, with evidence you can accept or reject.
              </p>
              <div className="mt-7 flex flex-col items-center justify-center gap-2.5 sm:flex-row">
                <Link href="/register" className="btn btn-primary w-full sm:w-auto">
                  Create a workspace
                </Link>
                <Link href="/login" className="btn btn-secondary w-full sm:w-auto">
                  Sign in with a demo account
                </Link>
              </div>
              <p className="mt-3 text-xs text-[var(--text-faint)]">No card needed · Demo accounts for all five roles in the README</p>
            </div>

            {/* Product sketch — a static representation of the suggestions inbox */}
            <div className="mx-auto mt-12 max-w-3xl">
              <div className="card overflow-hidden p-0 shadow-[var(--shadow-lg)]">
                <div className="flex items-center gap-1.5 border-b bg-[var(--bg-subtle)] px-3.5 py-2.5">
                  <span className="h-2.5 w-2.5 rounded-full bg-[#ff5f57]" />
                  <span className="h-2.5 w-2.5 rounded-full bg-[#febc2e]" />
                  <span className="h-2.5 w-2.5 rounded-full bg-[#28c840]" />
                  <span className="ml-2 text-[11px] text-[var(--text-faint)]">Auto-Pilot · Suggestions inbox</span>
                </div>
                <div className="space-y-2.5 p-3.5 sm:p-4">
                  <SuggestionSketch
                    title="Move PAY-1 to Code Review"
                    confidence="94%"
                    evidence="northwind/payments — feat(PAY-1): hosted checkout with card and UPI"
                    kind="pull request"
                  />
                  <SuggestionSketch
                    title="Flag PAY-6 as blocked"
                    confidence="92%"
                    evidence="#proj-pay — “I am stuck on PAY-6, the sandbox rate limit keeps tripping.”"
                    kind="chat message"
                  />
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Stat strip */}
        <section className="border-b bg-[var(--bg-subtle)]">
          <div className="mx-auto grid max-w-6xl grid-cols-2 gap-px px-4 py-8 sm:px-6 lg:grid-cols-4">
            <Stat value="5" label="Signals behind every health score" />
            <Stat value="0" label="Silent AI writes to your board" />
            <Stat value="4" label="Roles, enforced on the API" />
            <Stat value="1" label="Workspace instead of six tools" />
          </div>
        </section>

        {/* Features */}
        <section id="features" className="scroll-mt-16 border-b">
          <div className="mx-auto max-w-6xl px-4 py-14 sm:px-6 sm:py-20">
            <div className="max-w-2xl">
              <h2 className="text-2xl font-bold tracking-[-0.02em] sm:text-3xl">Everything a team needs, and three things nobody else ships</h2>
              <p className="mt-3 text-sm leading-relaxed text-[var(--text-muted)]">
                The base platform is complete — projects, tasks, sprints, docs, chat, files, time, analytics. The three highlighted below are what make the
                board trustworthy.
              </p>
            </div>
            <div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
              {FEATURES.map((feature) => (
                <div key={feature.title} className="card p-4 transition-colors hover:border-[var(--border-strong)]">
                  <div className="flex items-start justify-between gap-2">
                    <span className="text-xl" aria-hidden>
                      {feature.icon}
                    </span>
                    {feature.tag && <span className="badge bg-[var(--accent-soft)] text-[var(--accent)]">{feature.tag}</span>}
                  </div>
                  <h3 className="mt-2.5 text-sm font-semibold">{feature.title}</h3>
                  <p className="mt-1.5 text-[13px] leading-relaxed text-[var(--text-muted)]">{feature.body}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Pricing */}
        <section id="pricing" className="scroll-mt-16 border-b bg-[var(--bg-subtle)]">
          <div className="mx-auto max-w-6xl px-4 py-14 sm:px-6 sm:py-20">
            <div className="text-center">
              <h2 className="text-2xl font-bold tracking-[-0.02em] sm:text-3xl">Simple pricing</h2>
              <p className="mt-2 text-sm text-[var(--text-muted)]">Start free. Upgrade when the team outgrows it.</p>
            </div>
            <div className="mt-8 grid gap-4 lg:grid-cols-3">
              {PLANS.map((plan) => (
                <div
                  key={plan.name}
                  className={`card flex flex-col p-5 ${plan.featured ? 'border-[var(--accent)] shadow-[var(--shadow-lg)] lg:-translate-y-2' : ''}`}
                >
                  <div className="flex items-center justify-between">
                    <h3 className="text-sm font-semibold">{plan.name}</h3>
                    {plan.featured && <span className="badge bg-[var(--accent)] text-white">Most popular</span>}
                  </div>
                  <p className="mt-3 flex items-baseline gap-1.5">
                    <span className="text-3xl font-bold tracking-[-0.03em]">{plan.price}</span>
                    <span className="text-xs text-[var(--text-muted)]">{plan.cadence}</span>
                  </p>
                  <p className="mt-1 text-xs text-[var(--text-faint)]">{plan.seats}</p>
                  <ul className="mt-4 flex-1 space-y-2">
                    {plan.features.map((feature) => (
                      <li key={feature} className="flex items-start gap-2 text-[13px] text-[var(--text-muted)]">
                        <span className="mt-0.5 text-[var(--success)]" aria-hidden>
                          ✓
                        </span>
                        {feature}
                      </li>
                    ))}
                  </ul>
                  <Link href="/register" className={`btn mt-5 w-full ${plan.featured ? 'btn-primary' : 'btn-secondary'}`}>
                    {plan.cta}
                  </Link>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Testimonials */}
        <section id="testimonials" className="scroll-mt-16 border-b">
          <div className="mx-auto max-w-6xl px-4 py-14 sm:px-6 sm:py-20">
            <h2 className="text-2xl font-bold tracking-[-0.02em] sm:text-3xl">Teams that stopped chasing status</h2>
            <div className="mt-8 grid gap-4 lg:grid-cols-3">
              {TESTIMONIALS.map((item) => (
                <figure key={item.name} className="card flex flex-col p-5">
                  <blockquote className="flex-1 text-[13px] leading-relaxed text-[var(--text)]">“{item.quote}”</blockquote>
                  <figcaption className="mt-4 border-t pt-3">
                    <p className="text-[13px] font-semibold">{item.name}</p>
                    <p className="text-xs text-[var(--text-muted)]">{item.role}</p>
                  </figcaption>
                </figure>
              ))}
            </div>
          </div>
        </section>

        {/* FAQ */}
        <section id="faq" className="scroll-mt-16 border-b bg-[var(--bg-subtle)]">
          <div className="mx-auto max-w-3xl px-4 py-14 sm:px-6 sm:py-20">
            <h2 className="text-2xl font-bold tracking-[-0.02em] sm:text-3xl">Questions worth asking</h2>
            <div className="mt-6">
              <Faq items={FAQ} />
            </div>
          </div>
        </section>

        {/* Contact */}
        <section id="contact" className="scroll-mt-16">
          <div className="mx-auto max-w-3xl px-4 py-14 sm:px-6 sm:py-20">
            <h2 className="text-2xl font-bold tracking-[-0.02em] sm:text-3xl">Talk to us</h2>
            <p className="mt-2 text-sm text-[var(--text-muted)]">Tell us what your board looks like on a Friday afternoon.</p>
            <div className="mt-6">
              <ContactForm />
            </div>
          </div>
        </section>
      </main>

      <MarketingFooter />
    </div>
  );
}

function Stat({ value, label }: { value: string; label: string }) {
  return (
    <div className="px-2 py-3 text-center">
      <p className="text-2xl font-bold tracking-[-0.03em] text-[var(--accent)] sm:text-3xl">{value}</p>
      <p className="mt-1 text-[11px] leading-snug text-[var(--text-muted)]">{label}</p>
    </div>
  );
}

function SuggestionSketch({ title, confidence, evidence, kind }: { title: string; confidence: string; evidence: string; kind: string }) {
  return (
    <div className="rounded-xl border bg-[var(--bg)] p-3">
      <div className="flex items-start justify-between gap-3">
        <p className="text-[13px] font-semibold">{title}</p>
        <span className="badge shrink-0 bg-[var(--success-soft)] text-[var(--success)]">{confidence}</span>
      </div>
      <p className="mt-2 border-l-2 border-[var(--accent)] pl-2.5 text-[11px] leading-relaxed text-[var(--text-muted)]">
        <span className="font-medium text-[var(--text-faint)]">Evidence · {kind}</span>
        <br />
        {evidence}
      </p>
      <div className="mt-2.5 flex gap-1.5">
        <span className="btn btn-primary btn-sm pointer-events-none">Accept</span>
        <span className="btn btn-secondary btn-sm pointer-events-none">Reject</span>
      </div>
    </div>
  );
}
