import Link from 'next/link';
import type { Metadata } from 'next';
import { ContactForm, Faq, MarketingFooter, MarketingNav } from '@/components/marketing';
import { Hero } from '@/components/landing/hero';
import { AssemblySection } from '@/components/landing/assembly-section';
import { FeaturesInfographic } from '@/components/landing/features-infographic';
import { PricingSection } from '@/components/landing/pricing-section';
import { ScrollMotion } from '@/components/landing/motion';
import { Avatar } from '@/components/ui';

export const metadata: Metadata = {
  title: 'Loop — the project tool that keeps itself updated',
  alternates: { canonical: '/' },
};

/*
  The page stays a server component: all the copy ships as HTML and reads
  without JavaScript. Motion is layered on by <ScrollMotion />, which finds the
  `data-reveal` and `data-count` hooks below, and the two 3D scenes are client
  islands that load on their own.
*/

const TESTIMONIALS = [
  { quote: 'Our board used to be two days stale by Wednesday. Now it argues with us when it is wrong, and it shows the commit that proves it.', name: 'Ava Sharma', role: 'Head of Engineering, Northwind Labs' },
  { quote: 'The health score is the first project metric my team has not immediately dismissed, because you can see exactly which five numbers produced it.', name: 'Rohan Mehta', role: 'Product Manager, Northwind Labs' },
  { quote: 'As a client I get progress and shared docs, and nothing else. That boundary is the reason we approved the rollout.', name: 'Nina Fischer', role: 'Programme Lead, Fischer & Co' },
];

const FAQ = [
  { q: 'How is this different from Jira with a chatbot?', a: 'A chatbot answers questions about a board somebody else has to keep updated. Loop watches real activity — commits, pull requests, chat, task events — and proposes the update itself. Every proposal carries the trigger, the evidence and a confidence score, and a human accepts or rejects it. Accepting writes to the audit log.' },
  { q: 'Can the AI change my board without asking?', a: 'Not unless you switch it on. By default every suggestion waits in an inbox. A project owner can enable auto-apply per project, and even then only rule-based suggestions above 90% confidence apply automatically — AI-matched ones are capped below that line on purpose.' },
  { q: 'Is the health score generated by a language model?', a: 'No. The number is arithmetic: five signals, fixed weights, published formula. The model is handed the finished numbers and asked to write two sentences of plain English. It cannot invent a figure because it never computes one.' },
  { q: 'What stops a client from seeing internal discussion?', a: 'Permissions are applied before retrieval, not after. A client account has no chat permission at all, and workspace search and the AI retriever both filter to shared documents and task progress before anything reaches the model.' },
  { q: 'Which models does it use?', a: 'Groq runs as the frontier provider for speed, with Gemini as the automatic fallback if Groq is unavailable or rate limited. Embeddings for retrieval come from Gemini. Without any key configured the product still works — retrieval falls back to keyword search and the rules engine keeps making suggestions.' },
  { q: 'Does it work on a phone?', a: 'It is built mobile first. The board supports drag and drop on a pointer and tap-to-move on touch, navigation collapses to a bottom bar, and every table scrolls rather than squashing.' },
];

export default function LandingPage() {
  return (
    <div className="min-h-dvh">
      <ScrollMotion />
      <MarketingNav />

      <main id="main">
        <Hero />

        {/* Stat strip — the numbers count up as they arrive. */}
        <section className="border-b bg-[var(--bg-subtle)]">
          <div data-reveal-group className="mx-auto grid max-w-6xl 2xl:max-w-7xl 3xl:max-w-[88rem] grid-cols-2 gap-y-6 px-4 py-9 sm:px-6 lg:grid-cols-4">
            <Stat value={5} label="Signals behind every health score" href="/blog/explainable-health-score" />
            <Stat value={0} label="Silent AI writes to your board" href="/#faq" />
            <Stat value={4} label="Roles, enforced on the API" href="/blog/permission-aware-rag" />
            <Stat value={1} label="Workspace instead of six tools" href="/#features" />
          </div>
        </section>

        <AssemblySection />

        {/* Features — Transformed into Infographic Visual Layout */}
        <section id="features" className="scroll-mt-16 border-b">
          <div className="mx-auto max-w-6xl 2xl:max-w-7xl 3xl:max-w-[88rem] px-4 py-10 sm:px-6 sm:py-20">
            <div className="max-w-2xl 2xl:max-w-3xl mb-10">
              <h2 data-reveal className="text-[22px] font-bold leading-tight sm:text-[26px] sm:leading-normal md:text-4xl 2xl:text-5xl">
                Everything a team needs, and three things nobody else ships
              </h2>
              <p data-reveal className="mt-3 text-[14px] leading-relaxed text-[var(--text-muted)] sm:text-[15px] 2xl:text-lg">
                Visualized in real time: explore our self-updating engine, deterministic health math, and permission-filtered workspace RAG.
              </p>
            </div>
            
            <FeaturesInfographic />
          </div>
        </section>

        {/* Proof — what a suggestion actually looks like */}
        <section className="border-b bg-[var(--bg-subtle)]">
          <div className="mx-auto max-w-3xl 2xl:max-w-4xl 3xl:max-w-[64rem] px-4 py-10 sm:px-6 sm:py-20">
            <h2 data-reveal className="text-[22px] font-bold leading-tight sm:text-[26px] sm:leading-normal md:text-4xl 2xl:text-5xl">
              Nothing moves without evidence
            </h2>
            <p data-reveal className="mt-3 text-[14px] leading-relaxed text-[var(--text-muted)] sm:text-[15px] 2xl:text-lg">
              This is the inbox, not a mock-up of one. Every card names the trigger, quotes the source and scores its own confidence.
            </p>
            <div data-reveal className="mt-8">
              <div className="card overflow-hidden p-0 shadow-[var(--shadow-lg)]">
                <div className="flex items-center gap-1.5 border-b bg-[var(--bg-subtle)] px-3.5 py-2.5">
                  <span className="h-2.5 w-2.5 rounded-full bg-[var(--border-strong)]" />
                  <span className="h-2.5 w-2.5 rounded-full bg-[var(--border-strong)]" />
                  <span className="h-2.5 w-2.5 rounded-full bg-[var(--border-strong)]" />
                  <span className="ml-2 text-[11px] 2xl:text-xs text-[var(--text-faint)]">Auto-Pilot · Suggestions inbox</span>
                </div>
                <div className="space-y-2.5 p-3.5 sm:p-4 2xl:p-6">
                  <SuggestionSketch
                    title="Move PAY-1 to Code Review"
                    confidence="94%"
                    evidence="northwind/payments — feat(PAY-1): hosted checkout with card and UPI"
                    kind="pull request"
                  />
                  <SuggestionSketch
                    title="Flag PAY-6 as blocked"
                    confidence="92%"
                    evidence="#proj-pay — “I am stuck on PAY-6, the sandbox rate limit keeps tripping.”"
                    kind="chat message"
                  />
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Pricing — Indian Rupees & Razorpay Checkout Modal */}
        <PricingSection />

        {/* Testimonials */}
        <section id="testimonials" className="scroll-mt-16 border-b bg-[var(--bg-subtle)]">
          <div className="mx-auto max-w-6xl 2xl:max-w-7xl 3xl:max-w-[88rem] px-4 py-10 sm:px-6 sm:py-20">
            <h2 data-reveal className="text-[22px] font-bold leading-tight sm:text-[26px] sm:leading-normal md:text-4xl 2xl:text-5xl">
              Teams that stopped chasing status
            </h2>
            <div data-reveal-group className="mt-8 grid gap-4 lg:grid-cols-3 2xl:gap-6">
              {TESTIMONIALS.map((item) => (
                <figure key={item.name} className="card flex flex-col p-5 sm:p-6 2xl:p-7">
                  <blockquote className="flex-1 text-[14px] 2xl:text-base leading-relaxed">“{item.quote}”</blockquote>
                  <figcaption className="mt-5 flex items-center gap-3 border-t pt-4">
                    <Avatar name={item.name} size={36} />
                    <span className="min-w-0">
                      <span className="block truncate text-[13px] 2xl:text-sm font-semibold">{item.name}</span>
                      <span className="block truncate text-xs text-[var(--text-muted)]">{item.role}</span>
                    </span>
                  </figcaption>
                </figure>
              ))}
            </div>
          </div>
        </section>

        {/* FAQ */}
        <section id="faq" className="scroll-mt-16 border-b">
          <div className="mx-auto max-w-3xl 2xl:max-w-4xl 3xl:max-w-[64rem] px-4 py-10 sm:px-6 sm:py-20">
            <h2 data-reveal className="text-[22px] font-bold leading-tight sm:text-[26px] sm:leading-normal md:text-4xl 2xl:text-5xl">
              Questions worth asking
            </h2>
            <div data-reveal className="mt-6">
              <Faq items={FAQ} />
            </div>
          </div>
        </section>

        {/* Contact */}
        <section id="contact" className="scroll-mt-16 bg-[var(--bg-subtle)]">
          <div className="mx-auto max-w-3xl 2xl:max-w-4xl 3xl:max-w-[64rem] px-4 py-10 sm:px-6 sm:py-20">
            <h2 data-reveal className="text-[22px] font-bold leading-tight sm:text-[26px] sm:leading-normal md:text-4xl 2xl:text-5xl">
              Talk to us
            </h2>
            <p data-reveal className="mt-2 text-[14px] text-[var(--text-muted)] sm:text-[15px] 2xl:text-lg">
              Tell us what your board looks like on a Friday afternoon.
            </p>
            <div data-reveal className="mt-6">
              <ContactForm />
            </div>
          </div>
        </section>
      </main>

      <MarketingFooter />
    </div>
  );
}

/** Every figure here is a claim, and each one opens the page that backs it. */
function Stat({ value, label, href }: { value: number; label: string; href: string }) {
  return (
    <Link href={href} className="group block rounded-[var(--radius)] px-2 py-1 text-center transition-colors hover:bg-[var(--bg-inset)]">
      {/* Renders the final figure, so with no JavaScript the number is still
          right; the counter simply replaces it on the way in. */}
      <p data-count={value} className="text-4xl font-bold tabular-nums sm:text-5xl">
        {value}
      </p>
      <p className="mx-auto mt-1.5 max-w-[13rem] text-[11.5px] leading-snug text-[var(--text-muted)] group-hover:text-[var(--text)]">{label}</p>
    </Link>
  );
}

function SuggestionSketch({ title, confidence, evidence, kind }: { title: string; confidence: string; evidence: string; kind: string }) {
  return (
    <Link href="/login" className="group block rounded-[16px] border bg-[var(--bg)] p-3.5 transition-colors hover:border-[var(--border-strong)]">
      <div className="flex items-start justify-between gap-3">
        <p className="text-[13px] font-semibold">{title}</p>
        <span className="badge shrink-0 bg-[var(--success-soft)] text-[var(--success)]">{confidence}</span>
      </div>
      <p className="mt-2.5 border-l-2 border-[var(--text)] pl-3 text-[11.5px] leading-relaxed text-[var(--text-muted)]">
        <span className="font-semibold text-[var(--text-faint)]">Evidence · {kind}</span>
        <br />
        {evidence}
      </p>
      {/* These two are a picture of the controls, not the controls. Rendered
          small and muted so they read as part of the preview, with the card
          itself carrying the way to the real thing. */}
      <div className="mt-3 flex items-center gap-1.5">
        <span className="badge bg-[var(--bg-inset)] text-[var(--text-muted)]">Accept</span>
        <span className="badge bg-[var(--bg-inset)] text-[var(--text-muted)]">Reject</span>
        <span className="ml-auto text-[11px] font-medium text-[var(--accent)] group-hover:underline">Try it on a demo account →</span>
      </div>
    </Link>
  );
}
