'use client';

import { useState } from 'react';
import { Button, Card, SectionTitle, Skeleton } from '@/components/ui';
import { DonutChart, LineChart } from '@/components/charts';
import { Icon } from '@/components/icons';
import { useQuery } from '@/lib/hooks';
import { api, apiErrorMessage } from '@/lib/api';
import { useToast } from '@/components/providers/toast';
import { formatShortDate, healthTone } from '@/lib/format';

interface Signal {
  key: string;
  label: string;
  weight: number;
  penalty: number;
  contribution: number;
  detail: string;
  value: string;
}

interface Health {
  score: number;
  signals: Signal[];
  actions: { label: string; gain: number; signal: string }[];
  narrative: string | null;
  computedAt: string;
  sampleSize: { openTasks: number; totalTasks: number };
}

/**
 * The whole point of this panel is that a manager can see how the number was
 * produced: every signal shows its own value, weight and the exact points it
 * removed. Nothing here is generated by a model except the narrative line,
 * which is labelled as such.
 */
export function HealthPanel({ projectId }: { projectId: string }) {
  const toast = useToast();
  const [refreshing, setRefreshing] = useState(false);
  const { data, loading, refetch, setData } = useQuery<Health>(`/api/projects/${projectId}/health`, [projectId]);
  const { data: history } = useQuery<{ score: number; createdAt: string }[]>(`/api/projects/${projectId}/health/history`, [projectId]);

  if (loading && !data) return <Skeleton className="h-72 w-full" />;
  if (!data) return null;

  const tone = healthTone(data.score);
  const totalLost = data.signals.reduce((sum, s) => sum + s.contribution, 0);

  return (
    <div className="space-y-4">
      <Card>
        <div className="flex flex-col gap-4 sm:flex-row sm:items-start">
          <div className="flex items-center gap-4">
            <DonutChart value={data.score} size={104} color={tone.color} label="health" />
            <div>
              <p className="text-sm font-semibold" style={{ color: tone.color }}>
                {tone.label}
              </p>
              <p className="mt-0.5 text-xs text-[var(--text-muted)]">
                {data.sampleSize.openTasks} open of {data.sampleSize.totalTasks} tasks
              </p>
              <p className="mt-1 text-[11px] text-[var(--text-faint)]">Computed {formatShortDate(data.computedAt)}</p>
            </div>
          </div>

          <div className="flex-1">
            <p className="text-[13px] leading-relaxed">
              <span className="font-semibold">100</span>
              <span className="text-[var(--text-muted)]"> starting score, minus </span>
              <span className="font-semibold tabular-nums">{totalLost.toFixed(1)}</span>
              <span className="text-[var(--text-muted)]"> across five signals. The arithmetic is fixed — no model produces this number.</span>
            </p>
            {data.narrative && (
              <p className="mt-2 rounded-lg border-l-2 border-[var(--accent)] bg-[var(--accent-soft)]/50 px-3 py-2 text-[13px] leading-relaxed">
                <span className="mr-1 text-[10px] font-semibold uppercase tracking-wider text-[var(--accent)]">AI summary</span>
                {data.narrative}
              </p>
            )}
            <Button
              size="sm"
              className="mt-3"
              loading={refreshing}
              icon={<Icon.sparkles width={14} height={14} />}
              onClick={async () => {
                setRefreshing(true);
                try {
                  const { data: fresh } = await api.get<Health>(`/api/projects/${projectId}/health?refresh=true`);
                  setData(fresh);
                  toast.success('Health recomputed');
                } catch (caught: unknown) {
                  toast.error(apiErrorMessage(caught));
                } finally {
                  setRefreshing(false);
                }
              }}
            >
              Recompute and explain
            </Button>
          </div>
        </div>
      </Card>

      <Card>
        <SectionTitle title="How the score was produced" subtitle="Weights are fixed and published — every signal shows its own contribution" />
        <div className="space-y-2.5">
          {data.signals.map((signal) => (
            <div key={signal.key} className="rounded-lg border p-3">
              <div className="flex flex-wrap items-baseline justify-between gap-2">
                <p className="text-[13px] font-semibold">{signal.label}</p>
                <p className="text-xs tabular-nums">
                  <span className="font-mono text-[var(--text-muted)]">{signal.value}</span>
                  <span className="mx-1.5 text-[var(--text-faint)]">→</span>
                  <span className={signal.contribution > 0 ? 'font-semibold text-[var(--danger)]' : 'text-[var(--success)]'}>
                    {signal.contribution > 0 ? `−${signal.contribution}` : '0'}
                  </span>
                  <span className="text-[var(--text-faint)]"> of {signal.weight}</span>
                </p>
              </div>
              <div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[var(--bg-inset)]">
                <div className="h-full rounded-full bg-[var(--danger)] transition-[width] duration-500" style={{ width: `${signal.penalty * 100}%` }} />
              </div>
              <p className="mt-1.5 text-[11px] leading-relaxed text-[var(--text-muted)]">{signal.detail}</p>
            </div>
          ))}
        </div>
      </Card>

      {data.actions.length > 0 && (
        <Card>
          <SectionTitle title="Top three fixes" subtitle="Ranked by how many points each would return" />
          <ol className="space-y-2">
            {data.actions.map((action, index) => (
              <li key={action.signal} className="flex items-start gap-2.5 rounded-lg border p-3">
                <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-[var(--accent-soft)] text-[11px] font-bold text-[var(--accent)]">{index + 1}</span>
                <p className="flex-1 text-[13px] leading-snug">{action.label}</p>
                <span className="badge shrink-0 bg-[var(--success-soft)] text-[var(--success)]">+{action.gain}</span>
              </li>
            ))}
          </ol>
        </Card>
      )}

      {history && history.length > 1 && (
        <Card>
          <SectionTitle title="Trend" subtitle="One snapshot per day" />
          <LineChart
            height={140}
            series={[{ label: 'Health score', color: tone.color, points: history.map((point) => ({ x: formatShortDate(point.createdAt), y: point.score })) }]}
          />
        </Card>
      )}

      <button type="button" onClick={refetch} className="text-xs text-[var(--text-muted)] hover:underline">
        Refresh
      </button>
    </div>
  );
}
